persistence: "" # default memory
database:
  engine: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: ""
  password: ""
  name: ""
  maxOpenConns: 10
  maxIdleConns: 1
  connMaxLifetime: 60000000000
