timeout: 5
host: ":50000"
redis:
  # redis://user:pass@127.0.0.1:6379
  url: redis://127.0.0.1:6379
  maxIdle: 10
  maxActive: 500
  wait: true
  # second
  maxIdleTimeout: 10
mongodb:
  url: mongodb://127.0.0.1:27017

dgraph:
  url: 127.0.0.1:5080
  maxIdle: 10
  maxIdleTimeout: 10
